//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class periopContent
    {
        public int CourseID { get; set; }
        public string Description { get; set; }
        public string TemplateID { get; set; }
        public string CourseType { get; set; }
        public bool IsActive { get; set; }
    }
}
